var name = "nitesh";
var school = "masai";
var grade = 5;
var section = "B";
var rollno = 24;
var english = 76;
var hindi = 87;
var sanskrit = 78;
console.log(name);
console.log(school);
console.log(grade);
console.log(section);
console.log(rollno);
console.log(english);
console.log(hindi);
console.log(sanskrit);